name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  compart:
    name: mail.compartsoftware.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "08d6ee75890a687e032ba5439dd5e1ae"
          command: deploy
